Repository MISO-4203-E07/vinilos-movil, pull requests merged in 2021-11, with the labels that each got.

#31 Feature/hu01 list albumes
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/edu/uniandes/vinilos/data/.gitkeep
  app/src/main/java/co/edu/uniandes/vinilos/data/model/Album.kt
  app/src/main/java/co/edu/uniandes/vinilos/data/net/AlbumApi.kt
  app/src/main/java/co/edu/uniandes/vinilos/data/net/ApiClient.kt
  app/src/main/java/co/edu/uniandes/vinilos/data/net/RetrofitBroker.kt
  app/src/main/java/co/edu/uniandes/vinilos/util/.gitkeep
  app/src/main/java/co/edu/uniandes/vinilos/util/Attr.kt
  app/src/main/java/co/edu/uniandes/vinilos/view/MainActivity.kt
  app/src/main/java/co/edu/uniandes/vinilos/view/album/AlbumActivity.kt
  app/src/main/java/co/edu/uniandes/vinilos/view/album/AlbumAdapter.kt
  app/src/main/java/co/edu/uniandes/vinilos/viewmodel/.gitkeep
  app/src/main/java/co/edu/uniandes/vinilos/viewmodel/AlbumViewModel.kt
  app/src/main/res/layout/activity_album.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/template_item_album.xml
  app/src/main/res/values/strings.xml
Labels: HU001

#32 Feature/hu02 detail album
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/edu/uniandes/vinilos/data/model/Album.kt
  app/src/main/java/co/edu/uniandes/vinilos/data/model/Performer.kt
  app/src/main/java/co/edu/uniandes/vinilos/data/model/Track.kt
  app/src/main/java/co/edu/uniandes/vinilos/data/net/RetrofitBroker.kt
  app/src/main/java/co/edu/uniandes/vinilos/data/repositories/AlbumRepository.kt
  app/src/main/java/co/edu/uniandes/vinilos/util/Attr.kt
  app/src/main/java/co/edu/uniandes/vinilos/view/album/AlbumActivity.kt
  app/src/main/java/co/edu/uniandes/vinilos/view/album/AlbumAdapter.kt
  app/src/main/java/co/edu/uniandes/vinilos/view/album/DetailAlbumActivity.kt
  app/src/main/java/co/edu/uniandes/vinilos/view/main/MainActivity.kt
  app/src/main/java/co/edu/uniandes/vinilos/viewmodel/AlbumViewModel.kt
  app/src/main/res/drawable-hdpi/ic_vinilos_circle.png
  app/src/main/res/drawable-hdpi/ic_vinilos_square.png
  app/src/main/res/drawable-mdpi/ic_vinilos_circle.png
  app/src/main/res/drawable-mdpi/ic_vinilos_square.png
  app/src/main/res/drawable-v24/default_album_image.png
  app/src/main/res/drawable-xhdpi/ic_vinilos_circle.png
  app/src/main/res/drawable-xhdpi/ic_vinilos_square.png
  app/src/main/res/drawable-xxhdpi/ic_vinilos_circle.png
  app/src/main/res/drawable-xxhdpi/ic_vinilos_square.png
  app/src/main/res/drawable-xxxhdpi/ic_vinilos_circle.png
  app/src/main/res/drawable-xxxhdpi/ic_vinilos_square.png
  app/src/main/res/drawable/ic_round_add.xml
  app/src/main/res/drawable/ic_round_audiotrack.xml
  app/src/main/res/drawable/ic_round_broken_image.xml
  app/src/main/res/layout/activity_album.xml
  app/src/main/res/layout/activity_detail_album.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/template_item_album.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: HU002

#35 Add nav bar / HU003
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/ic_one-playstore.png
  app/src/main/java/co/edu/uniandes/vinilos/data/model/Performer.kt
  app/src/main/java/co/edu/uniandes/vinilos/data/net/ApiClient.kt
  app/src/main/java/co/edu/uniandes/vinilos/data/net/ArtistApi.kt
  app/src/main/java/co/edu/uniandes/vinilos/data/net/RetrofitBroker.kt
  app/src/main/java/co/edu/uniandes/vinilos/data/repositories/ArtistRepository.kt
  app/src/main/java/co/edu/uniandes/vinilos/view/MainActivity.kt
  app/src/main/java/co/edu/uniandes/vinilos/view/album/AlbumActivity.kt
  app/src/main/java/co/edu/uniandes/vinilos/view/album/AlbumFragment.kt
  app/src/main/java/co/edu/uniandes/vinilos/view/artist/ArtistAdapter.kt
  app/src/main/java/co/edu/uniandes/vinilos/view/artist/ArtistFragment.kt
  app/src/main/java/co/edu/uniandes/vinilos/view/main/MainActivity.kt
  app/src/main/java/co/edu/uniandes/vinilos/viewmodel/ArtistViewModel.kt
  app/src/main/res/drawable/ic_menu_gallery.xml
  app/src/main/res/drawable/ic_menu_slideshow.xml
  app/src/main/res/drawable/side_nav_bar.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/app_bar_main.xml
  app/src/main/res/layout/content_main.xml
  app/src/main/res/layout/fragment_album.xml
  app/src/main/res/layout/fragment_artist.xml
  app/src/main/res/layout/nav_header_main.xml
  app/src/main/res/layout/template_item_artists.xml
  app/src/main/res/menu/activity_bar_main_drawer.xml
  app/src/main/res/menu/main.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-w1240dp/dimens.xml
  app/src/main/res/values-w600dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: HU003

#40 Feature/general testing
  app/build.gradle
  app/src/androidTest/java/co/edu/uniandes/vinilos/MainTestSuite.kt
  app/src/androidTest/java/co/edu/uniandes/vinilos/base/BaseTest.kt
  app/src/androidTest/java/co/edu/uniandes/vinilos/view/album/AlbumActivityTest.kt
  app/src/androidTest/java/co/edu/uniandes/vinilos/view/album/AlbumTest.kt
  app/src/androidTest/java/co/edu/uniandes/vinilos/view/album/DetailAlbumActivityTest.kt
  app/src/androidTest/java/co/edu/uniandes/vinilos/view/artist/ArtistTest.kt
  app/src/androidTest/java/co/edu/uniandes/vinilos/view/collector/CollectorTest.kt
Labels: HU003
